### ISSUE TITLE
VideoJS on Firefox won't play videos recorded with VideoJS-Record on Chrome

### ISSUE THREAD

**Issue by praine** [collab-project/videojs-record#492] opened 2020-07-02 10:44 UTC
## Description
VideoJS on Firefox won't play videos recorded with VideoJS-Record on Chrome

## Steps to reproduce
Record a video with VideoJS-record on Chrome and try to play it on VideoJS on FF

### Expected
Video should render correctly

### Actual
VideoJS displays error

### Error output
The media could not be loaded, either because the server or network failed or because the format is not supported. 

## Additional Information
I have tried using the mimetypes specified here: https://collab-project.github.io/videojs-record/#/options
No success
#### videojs
7.8.2
#### browsers
Firefox 77.01
#### OSes
MacOS

**Comment by thijstriemstra** [comment] 2020-08-09 21:20
Looks related to this: https://github.com/muaz-khan/RecordRTC/pull/657

But you didn't specify what config you're using, and since webm is the default, that fix in recordrtc might help here as well.

**Comment by thijstriemstra** [comment] 2021-01-30 18:48
duplicate of #392

**Closed by thijstriemstra** 2021-01-30 18:48 UTC
