### ISSUE TITLE
Audio is distorted

### ISSUE THREAD

**Issue by v3ss0n** [collab-project/videojs-record#7] opened 2015-09-09 12:56 UTC
When recording audio at 22050 sample rate Sound is totally distored , sounds like an Alien. Tested on chrome 44.0.2403.155 ,  Linux Kernel 3.16 .

**Comment by thijstriemstra** [comment] 2015-09-10 11:14
Have you tried a different version of videojs-record or chrome and does it produce the same results?

**Comment by v3ss0n** [comment] 2015-09-10 11:36
Master and 0.8.14 tested. 
I tested on several different linux pc. All same Alien-sounding distorting :laughing: 
Increasing Samplerate to 440000 solve that problem tho.

**Comment by thijstriemstra** [comment] 2015-09-10 11:39
videojs-record uses recordrtc.js for the recording. Can you reproduce the problem with a standalone recordrtc example? If so it's a problem in that library...

**Comment by v3ss0n** [comment] 2015-09-10 11:45
We will just use 440000 for now. it works fine.

**Comment by thijstriemstra** [comment] 2015-09-11 19:54
Modified the title and removed the version nr reference because this is not related to a specific version of the plugin.

**Comment by thijstriemstra** [comment] 2015-09-24 00:37
I've changed the default rate to 44100. Closing this ticket, feel free to reopen with a solution..

**Closed by thijstriemstra** 2015-09-24 00:37 UTC
