### ISSUE TITLE
Can't load plugins in angular "Error: Could not load ffmpeg.wasm plugin"

### ISSUE THREAD

**Issue by stoogebag** [collab-project/videojs-record#601] opened 2021-08-17 02:39 UTC
## Description
Can't load plugins in Angular - 'could not load'

## Steps to reproduce
Follow install instructions to get angular project up and running. Then same for the plugin (eg ffmpeg-wasm) as in docs.

### Expected
Example working with record/transcode

### Actual
Error thrown on deviceReady, recorder unresponsive.

### Error output
The raw error output is 
![image](https://user-images.githubusercontent.com/4986492/129653905-81da8198-dc33-454a-bc06-f0d9a9ab5db8.png)

The inner exception, thrown away in videojs.record.js L1699 is 
![image](https://user-images.githubusercontent.com/4986492/129654011-194b58d9-54a7-4bf1-bc5e-7f805324cc16.png)
It seems like the _engineLoader is returning null for the ConvertEngineClass. 

Please bear with me as I am a .net dev new to js and angular and the way packages work here. It's possible that I'm not properly including something, but it all seems to be there - if videojs were missing then I'd expect the player/recorder not to work (everything is fine if no plugins are used). The line in the plugin docs:
![image](https://user-images.githubusercontent.com/4986492/129654242-c50db2ff-c540-4152-af4c-2c29f5578c83.png)
isn't 100pc clear to me in an Angular project. I think it seems unnecessary in Angular? I also tried bundling the script in the angular.json but that didn't fix anything. In any case, the error message displayed is not very informative.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
+-- video.js@7.14.3
+-- videojs-record@4.5.0
+-- @ffmpeg/core@0.10.0
+-- @ffmpeg/ffmpeg@0.10.1

#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
Chrome
Firefox
Edge

#### OSes
what platforms (operating systems and devices) are affected?
Android
Windows 10

**Comment by thijstriemstra** [comment] 2021-08-17 23:14
duplicate of #567?

**Comment by stoogebag** [comment] 2021-08-18 01:05
In my case the error occurs when you load the player, #567 seems to be fine until the actual conversion starts.

**Comment by thijstriemstra** [comment] 2021-08-18 11:28
> I think it seems unnecessary in Angular? 

It's definitely needed to include that script.

**Closed** 2021-08-18 11:29 UTC
Labels: plugins, needs-update

**Comment by stoogebag** [comment] 2021-08-18 13:13
By unnecessary I mean to say that I think in angular the files' inclusion gets handled by the import process. The code in question is literally just a vanilla angular project set up (for the repro) 
with vjs-record as in the docs, plus the plugin installation instructions (the import and then enabling it in the player options as in ffmpeg-wasm docs)

As for including the script explicitly, can anyone tell me how that's dont in an angular template? I can't just drop it into the component html <head> as far as I know. 
What I have tried is the following in my angular.json 
"scripts": [
              {
                "input": "node_modules/@ffmpeg/ffmpeg/dist/ffmpeg.min.js",
                "inject": true,
                "bundleName": "ffmpg"
              },]
and then in index.html's head:
  <script src="ffmpg.js"></script>

This appears to import the script through the whole project, but doesn't solve the issue. Project (minus node_modules) attached.

[vid.zip](https://github.com/collab-project/videojs-record/files/7007441/vid.zip)

**Comment by stoogebag** [comment] 2021-08-18 13:14
I also found an old closed ticket that seems to be the same issue on its surface: #507
