### ISSUE TITLE
Buttons cannot be clicked in mobile browsers.

### ISSUE THREAD

**Issue by v3ss0n** [collab-project/videojs-record#9] opened 2015-09-23 21:00 UTC
Is that related to Videojs or record? Buttons dosen't work when tested in mobile emulation (web dev tools). Not tested on native mobile browsers tho .

**Comment by thijstriemstra** [comment] 2015-09-24 17:19
Just tried with Firefox on Samsung Galaxy S4 and worked fine. What mobile browser(s) are you talking about? Closing this, reopen if you can reproduce on an actual mobile device, thanks.

**Closed by thijstriemstra** 2015-09-24 17:19 UTC
Labels: question

**Comment by v3ss0n** [comment] 2015-10-01 17:17
Hi , need to reopen this.

Tested on XperiaZ Ultra , google Chrome latest and buttons (even big button) cannot be tapped.

**Comment by v3ss0n** [comment] 2015-10-01 17:18
only maximize button and vol can be tapped

**Comment by v3ss0n** [comment] 2015-10-01 17:35
After soo many tries pressing big device button , and about 90 times pressing small rec button , able to record . But when trying to play back preview of rec , it get error 
![error](https://cloud.githubusercontent.com/assets/419606/10228533/5292a79e-6899-11e5-97d9-8939ff42fd14.jpg)

**Comment by v3ss0n** [comment] 2015-10-01 17:37
Tested with 3 different mobile devices , same problem. It all work fine on desktop . The demo tested is latest : http://collab-project.github.io/videojs-record/examples/audio-video.html

**Comment by thijstriemstra** [comment] 2015-10-01 19:00
Thanks for the research but I don't see any name, version or OS of the browser you're using?

**Comment by thijstriemstra** [comment] 2015-10-01 19:01
And how about a non-record version of the video.js demo, does it have the same problems?

**Comment by v3ss0n** [comment] 2015-10-01 19:29
All mobile devices tested are Android 4.4 . Tested with Videojs5 , it works fine. Haven't test with vidoejs4x.

**Comment by thijstriemstra** [comment] 2015-10-01 19:31
I think testing video.js 4.x would be best for now because v5.0 seems to have changed quite a lot.

**Comment by v3ss0n** [comment] 2015-10-01 19:35
It was reported in 4.x , https://github.com/videojs/video.js/issues/2333 which is closed since July? not sure it is resolved or not.

**Comment by v3ss0n** [comment] 2015-10-01 19:37
The related problem of non-auto-playback is also reported here https://github.com/videojs/video.js/issues/2502

**Comment by v3ss0n** [comment] 2015-10-01 19:39
So i guess , i am going to turnoff auto-playback.  Not possible via API i guess.
