### ISSUE TITLE
Is it possible to record only a specific HTML element?

### ISSUE THREAD

**Issue by seifsg** [collab-project/videojs-record#445] opened 2020-02-03 10:01 UTC
Hi!

We are working on an that edits small video and records it on the browser. I was wondering if your library can help with that. Thanks!

**Comment by thijstriemstra** [comment] 2020-02-03 13:49
can you elaborate, it's hard to guess what you exactly want to do.

**Comment by seifsg** [comment] 2020-02-03 18:17
@thijstriemstra Example: if I have a carousel/slideshow html element that is made in any library, example jQuery, is it possible for me to record that carousel while it is sliding ( with its animation ) and get a video out of that?

**Comment by thijstriemstra** [comment] 2020-02-05 09:59
Not yet.

Marking as duplicate of #288

**Closed by thijstriemstra** 2020-02-05 09:59 UTC
Labels: duplicate
