### ISSUE TITLE
Stop Recording not working

### ISSUE THREAD

**Issue by moumitacn** [collab-project/videojs-record#598] opened 2021-08-09 12:59 UTC
The recording stop and submit feature in not working Macbook, Iphone , Ipad (IOS devices) for both Safari and chrome platform. 

You can check the below link.
https://911us.us/
--- There you will find "Record Description of Incident" button of red colored.
Step 1 - Click  "Record Description of Incident" button
Step 2 - The recording popup will open, there you can start the recording, it will record, but neither it will stop nor Submit

Version - videojs-record 2.4.1
Non Working OS - IOS

Non-working Platforms : IOS chrome, Safari

**Comment by moumitacn** [comment] 2021-08-10 04:28
Waiting for your solution and update.

**Comment by arghadip** [comment] 2021-08-10 12:59
Hello, 

There is any solution? Please sugegst.

**Comment by moumitacn** [comment] 2021-08-11 07:53
Waiting for your support.

**Comment by thijstriemstra** [comment] 2021-08-16 23:36
Duplicate of #573

**Closed by thijstriemstra** 2021-08-16 23:36 UTC
Labels: duplicate, safari-desktop, safari-mobile
