### ISSUE TITLE
Replace Audio with the recorded data

### ISSUE THREAD

**Issue by JoeyChuuichi** [collab-project/videojs-record#446] opened 2020-02-06 08:31 UTC
## Description
I would like to use a music file as the audio track of the recorded video

## Steps to reproduce

Here is a failure case I have tried
```javascript
let music_track = new videojs.AudioTrack({
  id: "bgm",
  label: "Pre-set music",
  kind: "main"
})
player.audioTracks().addTrack(music_track);
player.record().stop();

player.on('finishRecord', function() {
    console.log('finished recording:', player.recordedData);
    upload(player.recordedData);
});
```

```html
<audio id="CutMusic">
  <source id="bgm" src="XXXX.wav">
</audio>
```
I wonder whether changing the audio track would affect the audio in ```player.recordedData```?
If no, is there any way to change the audio in recordedData?
#### browsers
Chrome

**Comment by thijstriemstra** [comment] 2020-02-06 12:43
No this is not possible (yet). You could play the music file using your internal audiocard instead of the microphone and record that, e.g.

![Screenshot from 2020-02-06 13-42-57](https://user-images.githubusercontent.com/305679/73938015-af5ce480-48e6-11ea-8cbd-d4ef8f4160a5.png)

**Comment by thijstriemstra** [comment] 2020-02-07 20:15
Looks like the `captureStream()` API allows you to do this, see #288.

Marking this as a duplicate of #288.

**Closed by thijstriemstra** 2020-02-07 20:15 UTC
