### ISSUE TITLE
Cannot use playbar in the record

### ISSUE THREAD

**Issue by JoeyChuuichi** [collab-project/videojs-record#396] opened 2019-09-05 13:22 UTC
## Description
Cannot find Playbar after replay the record.
For example, in this demo
https://videojs.com/advanced/#disneys-oceans
all the videos have play bars so that we can control the time of replay.

## Steps to reproduce
I am using the example of 
http://127.0.0.1:8080/examples/upload/simple.html

## Results
![image](https://user-images.githubusercontent.com/33302970/64345457-5cc38780-d02b-11e9-99f3-823f70cbd90e.png)

### Expected
Please describe what you expected to see.
![image](https://user-images.githubusercontent.com/33302970/64345479-664cef80-d02b-11e9-89af-e68c4b344372.png)

#### videojs
the latest
#### browsers
I am using chrome

**Comment by thijstriemstra** [comment] 2019-09-06 10:17
duplicate of #23

**Closed by thijstriemstra** 2019-09-06 10:17 UTC
Labels: duplicate

**Comment by JoeyChuuichi** [comment] 2019-09-08 11:42
@thijstriemstra 
I am sorry that when I try the [demo](https://collab-project.github.io/videojs-record/examples/video-only-ebml.html), it shows like this:

![image](https://user-images.githubusercontent.com/33302970/64487652-1e6ed800-d278-11e9-836c-ade145b78183.png)

**Comment by thijstriemstra** [comment] 2019-09-08 16:32
@JoeyChuuichi correct, that's how it's implemented right now. See #23 for an open ticket that also asks for the progress bar implementation.
