### ISSUE TITLE
Not Upload File on Chrome

### ISSUE THREAD

**Issue by jasvir899** [collab-project/videojs-record#194] opened 2017-12-15 05:16 UTC
I have Add the Code it Does;nt upload the Webm recorded file from chrome server, but its working on Mozila Firefox. and my url is HTTPS.
its just show the notification but file is not uploaded in backend

[webrecord.zip](https://github.com/collab-project/videojs-record/files/1561660/webrecord.zip)

**Comment by priMo-ex3m** [comment] 2017-12-19 15:41
Try that : 

in Firefox we have to use player.recordedData
in Chrome(as I used), that object has one more object key - video. So, to access that object we have to use : player.recordedData.video
To salve this cross-browser incompatibility with code :

 player.on('finishRecord', function() {
                if(player.recordedData.video == undefined) {
                    var videoFile = player.recordedData;
                } else {
                   var videoFile = player.recordedData.video;
                }
                console.log('finished recording: ', videoFile);
                // upload data to server
                var filesList = [videoFile];
                $('#fileupload').fileupload('add', {files: filesList});
            });

**Comment by thijstriemstra** [comment] 2017-12-27 17:31
thanks for the feedback @priMo-ex3m.

Marking this as a duplicate of #190

**Closed by thijstriemstra** 2017-12-27 17:31 UTC
Labels: duplicate
