### ISSUE TITLE
TS-Embl Does not Convert in Safari

### ISSUE THREAD

**Issue by tylerrowsell** [collab-project/videojs-record#581] opened 2021-05-25 14:04 UTC
## Description
Safari recently added support for webm. However when the ts-eml convertEngine attempts to convert it returns an error.
![image](https://user-images.githubusercontent.com/17143722/119511255-39c99180-bd40-11eb-82c0-3056d8fb22b7.png)
 
## Steps to reproduce
Open demo in safari and record 
https://collab-project.github.io/videojs-record/demo/video-only-ebml.html

### Expected
Expect conversion to complete.

### Actual
Conversion does not complete

### Error output
```
Unhandled Promise Rejection: Error: Unrepresentable length: 9 0000001c6674797069
```

#### videojs
7.11.8
#### videojs-record
4.4.0
#### browsers
Safari
#### OSes
MacOS/iOS

**Comment by thijstriemstra** [comment] 2021-08-16 23:21
marking this as a duplicate of #595 (that mentions a fix).

**Closed by thijstriemstra** 2021-08-16 23:21 UTC
Labels: plugins, safari-desktop, safari-mobile
