### ISSUE TITLE
saved video has mime type video/x-matroska

### ISSUE THREAD

**Issue by engr-zeeshan** [collab-project/videojs-record#469] opened 2020-05-11 20:42 UTC
## Description
Even with videoMimeType: "video/webm;codecs=H264" , I am getting video/x-matroska as mime-type of saved video and video has unknown duration due to which it does not has seekbar.

## Additional Information
` "myVideo", {
                controls: true,
                fluid: false,
                width: videoWidth,
                height: videoHeight,
                plugins: {
                    record: {
                        audio: true,
                        video: video_option_settings,
                        screen: record_screen_option,
                        frameWidth: videoWidth,
                        frameHeight: videoHeight,
                        maxLength: videoMaxLengthInSeconds,
                        debug: true,
                        videoMimeType: "video/webm;codecs=H264"
                    },
                },
            },`

#### videojs
what version of videojs does this occur with?
3.11.0

#### browsers

**Chrome Version**
81.0.4044.138 (Official Build) (64-bit)

**OS**
Windows 10

**Comment by thijstriemstra** [comment] 2020-05-11 20:57
Known issue at this point. Not marking it as a duplicate of #464 because that enhancement should fix this bug.

**Comment by engr-zeeshan** [comment] 2020-05-12 01:18
@thijstriemstra any idea how have they implemented? video saved by this plugin has known duration and also correct mime-type

**Comment by thijstriemstra** [comment] 2020-05-18 23:43
what operating system does this happen on? what version of chrome?

**Comment by engr-zeeshan** [comment] 2020-05-19 00:17
@thijstriemstra 
**Chrome Version**
81.0.4044.138 (Official Build) (64-bit)
**OS**
Windows 10

**Comment by thijstriemstra** [comment] 2020-05-19 00:40
Try using a supported codec for your browser. See https://www.webrtc-experiment.com/RecordRTC/simple-demos/isTypeSupported.html (`videoMimeType: 'video/webm;codecs=vp8'` for example).

**Comment by thijstriemstra** [comment] 2020-05-19 00:41
> video saved by this plugin has known duration and also correct mime-type

You should try the [ts-ebml](https://collab-project.github.io/videojs-record/#/plugins/ts-ebml) plugin to save the duration.

**Comment by pratibha31** [comment] 2020-05-19 15:06
> > video saved by this plugin has known duration and also correct mime-type
> 
> You should try the [ts-ebml](https://collab-project.github.io/videojs-record/#/plugins/ts-ebml) plugin to save the duration.

I changed videoMimetype to 'video/webm;codecs=vp8', still video is not playing in preview.

Version :  VIDEOJS: Using video.js 7.2.3 with videojs-record 2.4.1 and recordrtc 5.4.9
Operating System - Windows 10
Browser - Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
finished recording:  
      {video: Blob}
      video: Blob
      lastModified: 1589900380493
      lastModifiedDate: Tue May 19 2020 20:29:40 GMT+0530 (India Standard Time) {}
      name: "1589900380493.webm"
      size: 1252831
     type: "video/webm;codecs=vp8,opus"
    __proto__: Blob
   __proto__: Object

**Comment by thijstriemstra** [comment] 2020-05-19 15:19
The fix for this is in this pull request: #474 Give that a try or wait for v4.0.0 release.

**Closed** 2020-05-19 23:01 UTC
Labels: bug

**Comment by engr-zeeshan** [comment] 2020-05-20 18:23
> > video saved by this plugin has known duration and also correct mime-type
> 
> You should try the [ts-ebml](https://collab-project.github.io/videojs-record/#/plugins/ts-ebml) plugin to save the duration.

Thanks for sharing this; i gave it a try but could not get required result

**Comment by thijstriemstra** [comment] 2020-05-20 18:59
v4.0 should have correct mime-type, e.g. file extension of .mkv, right?

**Comment by engr-zeeshan** [comment] 2020-06-19 05:48
@thijstriemstra , I cannot find videojs-record-version.zip file for version4. I have been using .js file from dist folder of previous version. Could you please upload that ?

**Comment by thijstriemstra** [comment] 2020-06-19 11:46
@engr-zeeshan try https://registry.npmjs.org/videojs-record/-/videojs-record-4.0.0.tgz
