### ISSUE TITLE
Chrome crashes when recording audio and using more than on browser tab

### ISSUE THREAD

**Issue by marianabm** [collab-project/videojs-record#329] opened 2019-02-05 16:38 UTC
## Description
Audio recording crashes the browser when an audio is recording in one tab and the user is in another tab.

## Steps to reproduce
 - Start to record an audio
- Open a new tab on browser.
- Stay for a while in the other tab (at least 3 minutes) and do not pause the audio record in the first tab 
-  Go back to the tab that is recording the audio

### Expected
Audio is recording

### Actual
Browser crashes

### Error output
No errors.

### versions
videojs v7.5.0
videojs-record v3.3.0
RecordRTC v5.5.1
wavesurfer v2.1.3
#### browsers
what browser(s) are affected? 
Chrome and Opera
#### OSes
what platforms (operating systems and devices) are affected?
Windows and Linux

**Comment by thijstriemstra** [comment] 2019-02-05 19:07
@marianabm what version of Chrome? What version of windows/linux? Does it also happen with videojs-record 3.4.0?

**Comment by marianabm** [comment] 2019-02-06 11:30
Chrome 71.0.3578.80
Window 7, Linux Mint and Ubuntu.
I couldn't  be able to test with videojs-record 3.4.0 because of a package version conflict.

video.js requires safe-json-parse 4.0.0 
recordrtc 5.5.3 requires another dependency that requires safe-json-parse ~1.0.1
![dependencies](https://user-images.githubusercontent.com/9094746/52338509-c1fdbe80-29f1-11e9-96ef-c6f3746f9402.png)

**Comment by thijstriemstra** [comment] 2019-02-06 18:34
> recordrtc 5.5.3 requires another dependency that requires safe-json-parse ~1.0.1

Can you try 5.5.4?

ps. I could not reproduce this (tested with Chrome 71 on Ubuntu 16)

**Comment by marianabm** [comment] 2019-02-07 12:30
I tested with videojs-record 3.4.0 and it seems that it's taking more time for the problem happen on Chrome.
With Opera 58.0.3135.53, it crashes with a 3 minutes audio. 
But with Chrome it was necessary a longer audio (20 minutes). My screen froze, but after some minutes it got back to normal.

**Comment by thijstriemstra** [comment] 2019-02-09 00:32
@marianabm when does it crash? Can you launch chrome with `--enable-logging --v=1` and check the `chrome_debug.log file` in the user data dir for any errors: https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md

**Comment by thijstriemstra** [comment] 2019-02-10 22:32
It's probably wavesurfer.js that eats up all the memory, e.g. https://github.com/katspaugh/wavesurfer.js/issues/1498

**Comment by thijstriemstra** [comment] 2019-02-24 23:13
no feedback, closing.

**Closed by thijstriemstra** 2019-02-24 23:13 UTC
Labels: needs-update

**Comment by marianabm** [comment] 2019-02-25 15:46
Sorry for the delay.
I enabled logging on Chrome and no error message is shown, but the problem is still happening.
[chrome_debug.log](https://github.com/collab-project/videojs-record/files/2901195/chrome_debug.log)

Is there any way to test videojs-record without wavesurfer.js? I tried to remove the wavesurfer params, but I got an console error.
