### ISSUE TITLE
How to do add my logo image when record video via my webcam

### ISSUE THREAD

**Issue by AngelosR** [collab-project/videojs-record#424] opened 2019-12-09 10:38 UTC
Hi How are you. I am AngelosR.
Thanks for you videojs plugin.
I want to add my logo image when record video via my webcam using videojs-record.
I want to record video together my logo image.
If possible, please explain how to implement it in Vue.js. 
But, The implementation in vanilla js is fine too.
I am waiting your solution.
Thanks and Regard.

**Comment by thijstriemstra** [comment] 2020-01-12 20:06
Duplicate of #288

**Closed by thijstriemstra** 2020-01-12 20:06 UTC
Labels: duplicate
