### ISSUE TITLE
Audio only recording on Safari iOS 14.2

### ISSUE THREAD

**Issue by ignl** [collab-project/videojs-record#524] opened 2020-11-22 11:23 UTC
## Description
When trying audio only demo with IOS safari at first everything works fine, but when trying to play recording wavesurfer stops working and there are no audio.

## Steps to reproduce
Check audio-only demo with IOS safari (not sure about Mac safari).

### Expected result
Being able to play recorded audio and wavesurfer plugin working correctly.
It's possible that it's Safari problem, so maybe it makes sense to wait for next version which should have [fixes](https://bugs.webkit.org/show_bug.cgi?id=85851) for MediaRecorder api.

## Additional Information
IOS 14.2 with Safari 14.0.1 on Ipad Pro

**Comment by ignl** [comment] 2021-01-03 20:47
Hi, I have tested with IOS 14.3 and now it's possible to record audio (and video), however in demo it's still not possible to play what's recorded so it's a valid bug.

**Comment by thijstriemstra** [comment] 2021-01-05 16:36
can you download and attach a copy of the recorded audio file?

**Comment by thijstriemstra** [comment] 2021-01-31 23:28
@ignl can you try with iOS >= 14.4 and a `audioMimeType` of `audio/mp4`?

**Comment by thijstriemstra** [comment] 2021-03-03 20:40
> can you try with iOS >= 14.4

I tested the online [audio-only example](https://collab-project.github.io/videojs-record/demo/audio-only.html) with videojs-record 4.2.0 and video.js 7.11.4 in Mobile Safari for iOS 14.4 and this is the output of Mobile Safari console log:

```
[Log] RecordRTC version:  – "5.6.1" (RecordRTC.js, line 53)
[Log] started recording audio stream. (RecordRTC.js, line 63)
[Log] Using recorderType: – "MediaStreamRecorder" (RecordRTC.js, line 1057)
[Log] Passing following config over MediaRecorder API. – {type: "audio", bufferSize: 4096, sampleRate: 44100, …} (RecordRTC.js, line 2104)
{type: "audio", bufferSize: 4096, sampleRate: 44100, numberOfAudioChannels: 2, disableLogs: false, …}Object
[Log] Recorder state changed: – "recording" (RecordRTC.js, line 713)
[Log] Initialized recorderType: – "MediaStreamRecorder" – "for output-type:" – "audio" (RecordRTC.js, line 103)
[Log] started recording! (audio-only.html, line 97)
[Log] Stopped recording audio stream. (RecordRTC.js, line 129)
[Log] Recorder state changed: – "stopped" (RecordRTC.js, line 713)
[Log] audio/mp4 – "->" – "118 KB" (RecordRTC.js, line 170)
[Log] finished recording:  – Blob {lastModified: 1614803515711, lastModifiedDate: Wed Mar 03 2021 21:31:55 GMT+0100 (CET), name: "1614803515711.m4a", …} (audio-only.html, line 104)
Blob {lastModified: 1614803515711, lastModifiedDate: Wed Mar 03 2021 21:31:55 GMT+0100 (CET), name: "1614803515711.m4a", size: 117974, type: "audio/mp4", …}Blob
[Log] VIDEOJS: – "Pause microphone" (video.min.js, line 12)
[Log] VIDEOJS: – "Loading object: {\"lastModified\":1614803515711,\"lastModifiedDate\":\"2021-03-03T20:31:55.711Z\",\"name\":\"1614803515711.m4a\"}" (video.min.js, line 12)
[Log] VIDEOJS: – "Waveform is ready" (video.min.js, line 12)
[Log] VIDEOJS: – "Start playback" (video.min.js, line 12)
[Log] VIDEOJS: – "Finished playback" (video.min.js, line 12)
[Log] VIDEOJS: – "Pause playback" (video.min.js, line 12)
```

As you can see it recorded using `audio/mp4` and created an `m4a` file.

Make sure you set the `audioMimeType` to `audio/mp4` when recording audio-only with Safari:

```javascript
options.plugins.record.audioMimeType = 'audio/mp4';
```

> however in demo it's still not possible to play what's recorded so it's a valid bug.

I am not able to reproduce this, closing. Please re-open if you're still seeing this issue.

**Closed by thijstriemstra** 2021-03-03 20:40 UTC
Labels: safari-mobile
