### ISSUE TITLE
current time and duration blinking 

### ISSUE THREAD

**Issue by bobyper** [collab-project/videojs-record#175] opened 2017-10-26 11:23 UTC
## Description
for version 2.0.0 
if duration time is greater than 9 minutes, for example 10 minutes,  during second and every next record, current time and duration is blinking weird 

## Steps to reproduce
set maxLength: 600
make short record for example 5 seconds
make another record and watch into current time and duration

**Comment by thijstriemstra** [comment] 2017-10-26 15:20
@bobyper is this audio-video, video-only? both? audio-only?

**Comment by bobyper** [comment] 2017-10-26 15:41
i tested audio-video

**Comment by thijstriemstra** [comment] 2017-11-01 21:02
@bobyper I cannot reproduce this on Ubuntu 16.04 with Firefox 56. What browser. operating system, video.js versions?

**Comment by bobyper** [comment] 2017-11-02 16:08
windows - Firefox 56.0.2 and Chrome 61

The issue is caused from time format. Before start record current time and duration is showing as
0:00 / 10:00

start record -> current time is formatted as 
00:00 / 10:00 

reocrd 15 seconds and stop. Current time and duration is showing as

00:15 / 0:15

now duration of recorded stream is 0:15 but maxLength from recorder settings is 10:00 


Sometimes time is formatted as 
0:00 / 0:15  (duration of recorded string)
sometimes as
00:00 / 10:00 (duration of maxLength setting)

this cause current time and duration shifting and blinking during next records

**Comment by bobyper** [comment] 2017-11-23 08:10
I fixed this issue. Line 2792 version 2.0.2, function playbackTimeUpdate()
2792   this.setCurrentTime(this.player.currentTime(), this.streamDuration);

changed to
2792   if (!this.isRecording())  this.setCurrentTime(this.player.currentTime(), this.streamDuration);

setCurrentTime only in playback, not in record

**Comment by thijstriemstra** [comment] 2017-11-27 00:51
That sounds reasonable, thanks for the research @bobyper. Can you make a pull request so this fix can be properly accredited to you?

**Comment by thijstriemstra** [comment] 2017-12-04 23:16
> The issue is caused from time format. Before start record current time and duration is showing as
0:00 / 10:00

Check.

> start record -> current time is formatted as
> 00:00 / 10:00

Yep.

> reocrd 15 seconds and stop. Current time and duration is showing as
> 00:15 / 0:15

I see this as well now, thanks for the details. This is a bug.

And I also see the blinking bug now: simply make another recording and it starts shifting. I'll take a look if your suggestion fixes it for all cases.

**Comment by thijstriemstra** [comment] 2017-12-05 00:00
@bobyper I committed a fix to master, can you see if that one helps?

**Comment by bobyper** [comment] 2017-12-05 09:59
Working fine for me. Good job!

**Comment by thijstriemstra** [comment] 2017-12-05 18:47
thanks for the feedback.

**Closed by thijstriemstra** 2017-12-05 18:47 UTC
Labels: bug
