### ISSUE TITLE
why playing as online?

### ISSUE THREAD

**Issue by baimurzin** [collab-project/videojs-record#144] opened 2017-05-03 01:37 UTC
After I finished recording I destroy recorder player. Create new player videojs:

   
```
                var blob = URL.createObjectURL(vPlayer.recordedData.video);
               
                playerRecordPreview = videojs(playerRecordPreviewId, {
                    controlBar: {
                        children: {
                            playToggle: {},
                            volumeMenuButton: {},
                            progressControl: {},
                            currentTimeDisplay: {},
                            timeDivider: {},
                            durationDisplay: {},
                            liveDisplay: {},
                            fullscreenToggle: {}
                        }
                    }
                });
                playerRecordPreview.src({src: blob});
                playerRecordPreview.play();

```

`                <video id="playerRecordPreviewId" class="video-js vjs-default-skin" style="width: 100%; height: 100%;" controls></video>
`

And when its appear there is a bug, in control panel at first time instead of timer I see "ONLINE", but after I finish and play again it's OK. 

![image](https://cloud.githubusercontent.com/assets/13979141/25645762/34d8d19e-2fba-11e7-8746-bd536b65e9bd.png)

**Comment by thijstriemstra** [comment] 2017-05-03 01:49
@baimurzin you haven't read the ticket reporting instructions;

* what's the operating system
* video.js version, videojs-record version
* browser version(s)

**Comment by baimurzin** [comment] 2017-05-03 12:53
@thijstriemstra ok, sorry.
- MacOS Sierra 10.12.4
- Video.js 5.17.0, RecordRTC v5.4.1, videojs-record: ^1.5.2
- Google Chrome 57.0.2987

**Comment by thijstriemstra** [comment] 2017-05-04 00:56
Thanks. @baimurzin this [line](https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L497) should disable that component.

You shouldn't use an empty object but a boolean value instead: https://github.com/collab-project/videojs-record#customizing-controls

```javascript
controlBar: {
    // hide volume and fullscreen controls
    volumeMenuButton: false,
    fullscreenToggle: false
},
```

Closing, please reopen if issue is still there.

**Closed by thijstriemstra** 2017-05-04 00:56 UTC

**Comment by baimurzin** [comment] 2017-05-04 10:24
No, It doesn't' help, problem is still exist

**Comment by thijstriemstra** [comment] 2017-05-04 15:00
Can you please create a full example that reproduces this problem? I'm unable to reproduce it like this.
