### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by ViktorLalev** [collab-project/videojs-record#138] opened 2017-03-10 10:51 UTC
## Description
Hi, as you probably know there is an issue with accessing web cam and microphone via Safari.

This is the error i recieve:

> VIDEOJS: ERROR: 
> Error line: 395
> message: "Can't find variable: Promise"
> sourceId: 2092973536

I found that Safari don't currently support getUserMedia 

Is there any solutions to resolve this issue ?

**Comment by thijstriemstra** [comment] 2017-03-10 20:33
Duplicate of #85, also see #106 for Flash support.

**Closed by thijstriemstra** 2017-03-10 20:33 UTC
Labels: duplicate
