### ISSUE TITLE
Re-register events

### ISSUE THREAD

**Issue by jjones3535a** [collab-project/videojs-record#66] opened 2016-04-06 16:59 UTC
I am using -> player.recorder.destroy();  and then rebuilding my player on a page.  However, when I do this my player events:

player.on('deviceError',
player.on('deviceReady'
player.on('startRecord',

no longer fire.  Is there a way to re-register those events on the page?

**Comment by thijstriemstra** [comment] 2016-04-12 12:24
That would be a bug, can you create an example that reproduces this?

**Comment by thijstriemstra** [comment] 2016-04-17 17:50
@jjones3535a closing because of missing feedback.

**Closed by thijstriemstra** 2016-04-17 17:50 UTC
