### ISSUE TITLE
Blinking time indicator on second recording

### ISSUE THREAD

**Issue by alsar** [collab-project/videojs-record#46] opened 2016-01-20 17:16 UTC
If you record a video for the second time, the time indicator starts to blink.
Also the recording time is wrong. If the length of the recorded video is 10s the recorder shows 8s. This also happens on the second run.

**Comment by thijstriemstra** [comment] 2016-01-21 11:07
@alsar is this something you noticed in v1.1.0 or was it already present?

**Comment by alsar** [comment] 2016-01-21 12:07
It was already present in 1.0.3

**Comment by thijstriemstra** [comment] 2016-01-25 14:42
@alsar what browser are you using? It is supposed to blink (but perhaps it only does it the second time in your browser).

**Comment by thijstriemstra** [comment] 2016-01-25 14:43
Oh you mean the time indicator, not the record indicator of course, my bad. The time indicator starts to blink, can you make a gif or something of this, I'm not seeing this or misunderstanding you. This would also help with figuring out the recording time issue.

**Comment by alsar** [comment] 2016-01-25 17:04
Here is a video: https://youtu.be/g_QsgwQRqO4

As already mentioned, this happens only on the second run (and every next).

**Comment by vojka** [comment] 2016-02-01 08:19
I'm also having the same problem.

**Comment by thijstriemstra** [comment] 2016-02-02 16:07
It seems this only happens on slow machines, I can't reproduce it on this early 2015 Macbook Pro.

**Comment by alsar** [comment] 2016-02-04 14:27
Tried on multiple i5 machines with 8-16gb ram. Same problem.

**Comment by thijstriemstra** [comment] 2016-02-04 14:32
There is someting in video.js that resets the current time every x milliseconds when no valid source was found. This is what makes the time indicator 'blink'. Please look through the video.js source (probably for `timeupdate` event) and figure out how to disable this, I won't have time the next few days.

**Comment by thijstriemstra** [comment] 2016-02-04 14:39
For example, on https://github.com/videojs/video.js/blob/master/src/js/player.js#L2792:

```
/**
 * Fired when the current playback position has changed *
 * During playback this is fired every 15-250 milliseconds, depending on the
 * playback technology in use.
 *
 * @event timeupdate
 */
```
This is the 15-250 ms time indicator reset issue I think.

**Comment by thijstriemstra** [comment] 2016-02-04 14:47
And then in [tech.js](https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js#L165) there's `trackCurrentTime`. Can you check if that method is called and resets the time to 0?

**Comment by thijstriemstra** [comment] 2016-02-04 14:56
When the videojs-record plugin is first intialized, the `timeupdate` event [is disabled](https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L371). Then during playback it's [enabled again](https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L955). If you then start recording again, the `timeupdate` handler is [disabled again](https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L1295). I suspect this is where something's wrong..

**Comment by thijstriemstra** [comment] 2016-03-16 01:54
@alsar can you upgrade video.js to 5.8.0 or newer and check if this issue is fixed (related commit: https://github.com/videojs/video.js/commit/04907283216c18fdcb44bebd1253c507b5cede51)?

**Comment by alsar** [comment] 2016-03-16 08:24
@thijstriemstra it's still the same with 5.8.3

**Comment by zang** [comment] 2016-03-23 21:22
Got the same issue. Time still updates, but the leading 0 seems to blink. (e.g. 0:12 to 00:12, then to 0:13)

**Comment by zang** [comment] 2016-03-24 13:59
it works fine if I change line 1547 to the following:
m = ((h && m < 10) ? '0' + m : m) + ':';

I am not unsure what's the gm for, so didn't create PR.

**Comment by thijstriemstra** [comment] 2016-03-24 17:39
@zang feel free to make a PR so I can check it out. videojs-wavesurfer also uses the same code, I'm guessing it's the same problem there? https://collab-project.github.io/videojs-wavesurfer

**Comment by zang** [comment] 2016-03-24 20:50
https://github.com/collab-project/videojs-record/pull/65

**Comment by thijstriemstra** [comment] 2016-03-25 15:16
This is the original code btw: https://github.com/videojs/video.js/blob/master/src/js/utils/format-time.js

videojs-record adds support for `M:SS:MMM`.

**Comment by thijstriemstra** [comment] 2016-03-25 15:49
Thanks for the PR @zang, merged it and will release a new version now.

**Closed by thijstriemstra** 2016-03-25 15:49 UTC
Labels: bug
