### ISSUE TITLE
[CRITICAL] Unable to record videos in ios Safari angular mobile project

### ISSUE THREAD

**Issue by MS-Vauld** [collab-project/videojs-record#592] opened 2021-07-15 11:44 UTC
## Description
Couldnt able to start the recording in angular mobile project for iOS. 

## Steps to reproduce
Follow the steps which is mentioned in videojs website for angular installation steps and usage and when i run the app, recording dint work

### Expected
Should start the recording

### Actual
throwing the error of "this browser is not supported for navigator.mediaDevices.getUserMedia"

### Error output
navigator.mediaDevices. is undefined

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
what version of videojs does this occur with?
#### videojs - latest version i am using

what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
#### Safari - 14.1.1
what platforms (operating systems and devices) are affected?
iOS

**Comment by thijstriemstra** [comment] 2021-07-21 00:26
duplicate of #573

**Closed by thijstriemstra** 2021-07-21 00:26 UTC
