### ISSUE TITLE
Firefox Video/audio issue.

### ISSUE THREAD

**Issue by aaagepard** [collab-project/videojs-record#147] opened 2017-05-10 14:09 UTC
## Description
FireFox 53.0.2 (32-bit) 
Audio-video example dont works normally.
It see webcam and microphone but after access acception, it just show loader and one first. Controls works as expected, but any display changes after start or stop recording.

Works great in Chrome. Thanks!

## Steps to reproduce
Used FireFox 53.0.2 (32-bit) 
Audio-video : https://collab-project.github.io/videojs-record/examples/audio-video.html

### Error output
No errors in console.

**Comment by thijstriemstra** [comment] 2017-05-10 21:57
@aaagepard hat operating system? and im not able to reproduce this with that version of Firefox on Ubuntu 16.04

**Comment by aaagepard** [comment] 2017-05-11 09:10
@thijstriemstra Windows 7

**Comment by aaagepard** [comment] 2017-05-12 09:39
I see, that wavesurfer.js microphone plugin doesnt works normally for me on example page - https://wavesurfer-js.org/plugins/microphone.html

After "Start the mic" click I see request to access the microphone and then no reaction on my voice, just horisontal line.

![firefor videoaudio issue issue 147 collab-projectvideojs-record - google chrome](https://cloud.githubusercontent.com/assets/25985568/25992673/00061da2-3710-11e7-8c50-5133ba53142c.jpg)

**Comment by aaagepard** [comment] 2017-05-12 09:41
Works fine in Chrome
![wavesurfer js - google chrome9848498489](https://cloud.githubusercontent.com/assets/25985568/25992783/55ed9dc6-3710-11e7-9b66-731029a9f526.jpg)

**Comment by thijstriemstra** [comment] 2017-05-12 16:50
@aaagepard can you open a ticket in wavesurfer.js for this? Once we figure out the issue there I can move on to solving it in other projects like this.

**Comment by aaagepard** [comment] 2017-05-13 09:02
@thijstriemstra  yes, of course. Issue created. https://github.com/katspaugh/wavesurfer.js/issues/1089

**Comment by thijstriemstra** [comment] 2017-06-13 02:23
> As I tested on my local, somesing wrong with audio. Just video works fine.

So is this a duplicate of #148 @aaagepard?

**Comment by aaagepard** [comment] 2017-06-13 11:11
@thijstriemstra  I think yes. we can remove this one.

**Closed** 2017-06-13 14:34 UTC
