### ISSUE TITLE
Turn Off Devices via javascript?

### ISSUE THREAD

**Issue by v3ss0n** [collab-project/videojs-record#12] opened 2015-09-25 22:26 UTC
``` vjsplayer.recorder.stop() ``` only stop recording , so need another function for turning off camera .
I don't want users to think that i am spying for NSA :stuck_out_tongue_closed_eyes:

**Comment by thijstriemstra** [comment] 2015-09-27 14:28
Sounds good, I'll add something like `stopAll` and/or `stopDevice`.

**Comment by v3ss0n** [comment] 2015-09-28 10:38
stopDevice sounds good.

**Comment by thijstriemstra** [comment] 2015-09-29 00:50
Added `stopDevice`, let me know if it works and I'll put out a new release.

**Comment by v3ss0n** [comment] 2015-09-29 08:45
Thanks , it is working. But i just upgraded to chrome 45 and getting depreciation Notices abobout MediaStream.stop()
found work arounds. But i think we need to support both ways as Chrome45 is relatively new and not everyone supported it yet.
https://developers.google.com/web/updates/2015/07/mediastream-deprecations

**Comment by v3ss0n** [comment] 2015-09-29 13:19
During audio-only mode : 

When i tried to stop and requestDevice , it just play the pre-recorded audio , didn't try to request device actually.

Might be a bug.

to test:

```javascript
//during AUDIO_ONLY
vjsrec.player().recorder.stopDevice();
vjsrec.player().recorder.getDevice();

```

**Comment by thijstriemstra** [comment] 2015-09-29 17:58
Yeah, stop and get are not working as expected yet. I added a fix for the deprecation warnings, could you check what happens with an older version of Chrome?

**Comment by thijstriemstra** [comment] 2015-09-29 18:02
Because it turns out https://github.com/collab-project/videojs-record/commit/4e071129f37461032491bc02ddf56de5e287fa2c broke the Chrome check so a 0.9.1 should be released asap.

**Comment by v3ss0n** [comment] 2015-09-29 20:55
I have no older version remained  , just did os upgrade. I will check after downloading.

**Comment by thijstriemstra** [comment] 2015-09-30 00:10
It was also a little wonky in modes other than audio-only, should be better now. Now going to look at the audio-only issue.

**Comment by thijstriemstra** [comment] 2015-10-04 19:57
Tested with Chromium 32 on OSX and seems the fix for deprecation works there as well so releasing 0.9.1 now, but still need to fix the audio-only issue.

**Comment by v3ss0n** [comment] 2015-10-04 22:04
```javascript
this.getUserMedia(
this.mediaType,
this.onDeviceReady.bind(this),
this.onDeviceError.bind(this));		                         
```
I tried replacing that in audio only . works partially , except it request media device two times and then fail to turnoff device.

**Comment by thijstriemstra** [comment] 2015-10-04 22:06
yeah i saw your PR but unfortunately the problem is a little further down the chain I think (in videojs-wavesurfer and/or wavesurfer.js microphone plugin).

**Comment by thijstriemstra** [comment] 2015-10-04 23:39
I think I have fixed it with https://github.com/collab-project/videojs-record/commit/2efca391b72d81057f351acb32702ab1b4cebb83 but it also requires some changes in the wavesurfer.js microphone plugin that I'll open a pull request for. Once that wavesurfer change is released I can roll a new release I suppose.

**Comment by thijstriemstra** [comment] 2015-10-06 00:10
Did some more fixes (as well as in videojs-wavesurfer and wavesurfer.js), should be better when the microphone PR is merged: https://github.com/katspaugh/wavesurfer.js/pull/542.

**Comment by thijstriemstra** [comment] 2015-10-06 08:55
If you upgrade to the latest wavesurfer.js (1.0.44) and microphone plugin, videojs-wavesurfer (0.9.9) and videojs-record 0.9.2 audio-only mode should work correctly. Please open a new ticket if there are new problems.

**Closed by thijstriemstra** 2015-10-06 08:55 UTC
Labels: enhancement

**Comment by v3ss0n** [comment] 2015-10-06 11:40
Thanks alot . Testing tonight.
