### ISSUE TITLE
Video is not playing in preview, after recording is complete

### ISSUE THREAD

**Issue by pratibha31** [collab-project/videojs-record#475] opened 2020-05-18 09:26 UTC
## Description
After recording when I am playing video in preview it is not playing.

## Additional Information
Below is recorded video details
finished recording:  
             {video: Blob}
                video: Blob
                lastModified: 1589793636945
                lastModifiedDate: Mon May 18 2020 14:50:36 GMT+0530 (India Standard Time) {}
                name: "1589793636945.x-matroska"
                size: 500038
                type: "video/x-matroska;codecs=avc1,opus"
                __proto__: Blob
                __proto__: Object

#### videojs
Using video.js 7.2.3
          videojs-record 2.4.1
          recordrtc 5.4.9
#### browsers
Google Chrome Version 81.0.4044.138
#### OSes
Windows 10

**Comment by thijstriemstra** [comment] 2020-05-18 23:43
what operating system does this happen on? what version of chrome?

What does your videojs-record config look like?

**Comment by thijstriemstra** [comment] 2020-05-19 00:38
duplicate of #469

**Closed by thijstriemstra** 2020-05-19 00:38 UTC
Labels: duplicate
