### ISSUE TITLE
[question] Can this be used to record augmented reality experiences?

### ISSUE THREAD

**Issue by marcusx2** [collab-project/videojs-record#621] opened 2021-11-07 16:59 UTC
I know it works to capture just the webcam feed, but what about other stuff on the screen? 

Please take a look at [ARjs](https://ar-js-org.github.io/AR.js-Docs/).  CTRL+F "Image Tracking Example". Try this [codepen](https://codepen.io/nicolocarpignoli/pen/vYOeYKd) on your phone, point the camera at [this picture](https://raw.githubusercontent.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex-image-big.jpeg).

I am wondering if videojs-record can capture the whole screen, including the webcamfeed and the augmented reality content as they show up to the user. And also if it works on mobile Safari. So in the example, can it capture the screen with the dinosaur? Thank you for your time.

**Comment by thijstriemstra** [comment] 2021-11-08 20:53
It's possible to record a browser window using screen capture option: https://github.com/collab-project/videojs-record/blob/master/examples/screen-only.html Not sure if that works on mobile safari, it likely doesn't.

**Comment by marcusx2** [comment] 2021-11-08 21:02
@thijstriemstra no, the api used in that example, [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API), isn't [available ](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API#browser_compatibility)on mobile.

It really needs to be something like [this example](https://collab-project.github.io/videojs-record/demo/audio-video.html). But instead of recording just webcam feed, it needs to record everything that is actually seen by the user. I take it it's not possible then? videojs can't record everything that's going on on the screen without using the Screen Capture API?

**Comment by thijstriemstra** [comment] 2021-11-08 21:08
I think you're looking for #288

**Comment by marcusx2** [comment] 2021-11-08 21:17
@thijstriemstra Thanks! This may be a viable solution. How can I do this with videojs-record? I don't want to use record-rtc directly or videojs-overlay. Can it be done with your library?

**Comment by thijstriemstra** [comment] 2021-11-08 21:24
It's an enhancement request. But shouldn't be hard to implement.. Pull requests welcome, I'm available to review something.

**Comment by marcusx2** [comment] 2021-11-08 21:25
Should I create a request for this? I don't know how to word it.

**Comment by thijstriemstra** [comment] 2021-11-08 21:26
No, basically this ticket is a duplicate of #288

**Comment by marcusx2** [comment] 2021-11-08 21:27
Ah ok. Are there any plans to have this feature anytime soon?

**Closed** 2021-11-09 00:18 UTC
Labels: duplicate, question
