### ISSUE TITLE
Issue record on iOS by Chrome

### ISSUE THREAD

**Issue by BabakSouth** [collab-project/videojs-record#701] opened 2023-12-30 09:21 UTC
## Description
Briefly describe the issue.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by squaloIT** [comment] 2024-01-31 11:11
The issue is not described at all. I have the issue on iOS on Chrome, as nothing gets recorded. On event finishRecord I get 0kb of the video. My app was working fine a month or two ago. I can provide more info if needed

**Comment by thijstriemstra** [comment] 2024-02-14 16:56
> The issue is not described at all. 

Yep, closing.

**Closed by thijstriemstra** 2024-02-14 16:56 UTC
