### ISSUE TITLE
the browser does not support navigator.mediaDevices.getDisplayMedia

### ISSUE THREAD

**Issue by onyxnl** [collab-project/videojs-record#412] opened 2019-10-24 08:26 UTC
## Description
I encounter this issue.

### Error output
the browser does not support navigator.mediaDevices.getDisplayMedia

#### videojs
VIDEOJS: Using video.js 7.6.5 with videojs-record 3.8.0 and recordrtc 5.5.9

#### browsers
Chrome (Version 77.0.3865.120)
#### OSes
Window 64bit

**Comment by thijstriemstra** [comment] 2019-10-24 11:04
that would be a pretty extreme bug; I will take a look.

**Comment by thijstriemstra** [comment] 2019-11-24 20:53
I cannot reproduce this, closing.

**Closed by thijstriemstra** 2019-11-24 20:53 UTC
Labels: can-not-reproduce
