### ISSUE TITLE
Upload video not on stop recording

### ISSUE THREAD

**Issue by priMo-ex3m** [collab-project/videojs-record#192] opened 2017-12-13 10:03 UTC
Ok, I have a form where you have to enter your info and then add a video. The problem is that with samples provided by this plugin, when video stops recording, it automatically .fileload the file with AJAX to server. 
There is a way how "on stop" recording to append this video to my <input type="file" name="video">, and then, when all the form is completed and user press Save, proceed the entire form ?

So, the issue is in appending the recorded video to input, not auto-load to server, and when the form is completed and submited by user, just then go with Ajax to a backend route that do the stuff?

**Comment by thijstriemstra** [comment] 2017-12-13 15:42
@priMo-ex3m can you show some example code (not the html, just javascript) that illustrates the problem?

**Comment by thijstriemstra** [comment] 2017-12-13 21:26
@priMo-ex3m is this what you're looking for?

https://github.com/collab-project/videojs-record/issues/172#issuecomment-338578813

**Comment by priMo-ex3m** [comment] 2017-12-14 08:10
Yes, thank you.

**Comment by thijstriemstra** [comment] 2017-12-14 08:20
Gonna mark this as a duplicate of #176.

**Closed by thijstriemstra** 2017-12-14 08:20 UTC
Labels: duplicate, question
