### ISSUE TITLE
Possible to Dynamically Handle If User Allows One/Denys Other? + Both Permissions At Once

### ISSUE THREAD

**Issue by GuyMight44** [collab-project/videojs-record#477] opened 2020-05-19 03:37 UTC
## Description

**Issue 1**
Let's say we have the [audio-screen.html](https://github.com/collab-project/videojs-record/blob/master/examples/audio-screen.html) example running. If the user allows screen capture but denies the microphone capture, the script fails. Is it not possible to just allow the screen capture then if the audio gets denied?

Issue 2:
In Firefox, after selecting which screen to record, Firefox jumps out of focus and focuses on the window you selected. However, because the audio permission box didnt appear yet, the recording does nothing. We have to click back on the Firefox window to force appear the audio permission and allow/deny that for it to actually start recording

## Steps to reproduce
**Issue 1:**
Allow the screen capture, deny the audio capture

**Issue 2:**
Select the screen u wish to capture, Firefox becomes out of focus

### Expected
**Issue 1:**
After denying the audio, it should record the screen without audio

**Issue 2:**
Instead of focusing on the window, it should ask all permissions needed before jumping

### Actual
Both explained as above

### Error output
Issue 1:
**Console outputs:** uncaught exception: Object

Issue 2:
Nothing on console output, something up with the coding itself

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Last version downloaded today (May 18, 2020)
#### browsers
Firefox 76.0.1 (64-bit) Stable
#### OSes
Windows 10

**Comment by thijstriemstra** [comment] 2020-05-19 19:58
> Issue 1: If the user allows screen capture but denies the microphone capture, the script fails. Is it not possible to just allow the screen capture then if the audio gets denied?

This is same issue as #463 

> In Firefox, after selecting which screen to record, Firefox jumps out of focus and focuses on the window you selected. However, because the audio permission box didnt appear yet, the recording does nothing. We have to click back on the Firefox window to force appear the audio permission and allow/deny that for it to actually start recording

I think this is a browser issue and not something we can fix. Please open a ticket for the Firefox browser and/or look in their bugzilla.

> Instead of focusing on the window, it should ask all permissions needed before jumping

This is definitely something you should open a new Firefox ticket for. I can't change the way their permissions system works.

So marking this as a duplicate of #463.

**Closed by thijstriemstra** 2020-05-19 19:58 UTC
Labels: duplicate

**Comment by thijstriemstra** [comment] 2020-05-19 20:14
The focus issue is also discussed here: https://stackoverflow.com/questions/60172910/is-it-possible-to-tell-the-browser-not-to-focus-bring-to-front-the-selected-wi

**Comment by GuyMight44** [comment] 2020-05-19 21:27
Hi @thijstriemstra Wouldnt it be a better idea then to put the screen sharing permission after the microphone or other permissions? Making the screen-sharing permission last?

**Comment by thijstriemstra** [comment] 2020-05-19 21:31
that sounds like a good idea but I'm not sure because someone else added this feature and added a comment that "order matters". 

```javascript
// join microphone track with screencast stream (order matters)
screenStream.addTrack(mic.getTracks()[0]);
this.onDeviceReady.bind(this)(screenStream);
```

Please open a new ticket and I'll take a look (for v4.1.0 or something).
