### ISSUE TITLE
Inconsistency between audio and video recordings

### ISSUE THREAD

**Issue by dirkk0** [collab-project/videojs-record#253] opened 2018-06-13 08:35 UTC
## Description
To copy recorded data to audio and video html elements, one needs to take different steps. In case of video, you can create a blob from recordedData.video with
```var blob = URL.createObjectURL(recorder.recordedData.video);``` but there is no such thing for audio.
Instead, you can create a binary blob from it, which seems to work at least for chrome.
```javascript
    var binaryData = [];
    binaryData.push(recorder.recordedData);
    blob = window.URL.createObjectURL(new Blob(binaryData))
```

What is the recommended way to copy audio data?

## Steps to reproduce
I put up an example here:
https://curious-electric.com/_temp/audio-video/

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
`VIDEOJS: Using video.js 7.0.3 with videojs-record 2.3.1 + videojs-wavesurfer 2.5.0 and recordrtc 5.4.6`
#### browsers
Chrome 66 (doesn't work on Firefox btw)
#### OSes
MacOS 10.12.6

**Comment by thijstriemstra** [comment] 2018-06-13 09:56
> Chrome 66 (doesn't work on Firefox btw

What doesn't work?

**Comment by dirkk0** [comment] 2018-06-17 12:00
In the upper audio side, it seems to be recording, but the waveform is a flat line. Playing yields silence.
Basically the same with the video part, except that the console shows

    VIDEOJS: ERROR: 
    TypeError: right-hand side of 'in' should be an object, got undefined
    Stack trace:
    shimCreateObjectURL/URL.createObjectURL@https://curious-electric.com/_temp/audio- video/adapter-latest.js:3911:1

**Comment by thijstriemstra** [comment] 2018-07-17 01:54
@dirkk0 the contents of `recordedData` varies between chrome and firefox. See https://github.com/collab-project/videojs-record/blob/master/src/js/engine/record-rtc.js#L137

Any suggestions how to improve this? Probably upstream in recordrtc?

**Comment by dirkk0** [comment] 2018-07-17 05:10
Since this is a record-rtc issue - yes.

**Comment by thijstriemstra** [comment] 2018-08-02 00:14
> the contents of recordedData varies between chrome and firefox.

At least it used to be like that. I double-checked and Chrome also produces a single blob now containing both audio and video, so there are no differences between chrome and firefox in recordrtc anymore.

So I'll change this in v3.0.0: `player.recordedData` will always be the blob with data in both browsers when recording audio + video, not `player.recordedData.video` in Chrome only anymore.

**Comment by thijstriemstra** [comment] 2018-08-02 00:29
> In the upper audio side, it seems to be recording, but the waveform is a flat line. Playing yields silence.

@dirkk0 I cannot reproduce this. Possibly a mic issue?

> but there is no such thing for audio.

There's also no inconsistency between `player.recordedData` in audio-only and `player.recordedData.video`: as in they're both Blobs?

**Comment by thijstriemstra** [comment] 2018-08-08 02:04
No feedback, closing.

**Closed by thijstriemstra** 2018-08-08 02:04 UTC
Labels: needs-more-info, question
