### ISSUE TITLE
Record from current video element and predef source

### ISSUE THREAD

**Issue by cubecleveland** [collab-project/videojs-record#419] opened 2019-11-24 20:16 UTC
Hello, im trying to record the currnet running video and not to opena camera.
So ive set the src attr to the current video.

But everytime i initazlie the plugin it automaticxally tryin to access the camera...
What is the way to record straight from the current element.

**Comment by thijstriemstra** [comment] 2019-11-24 20:34
This is something you can do with the captureStream() method (see https://developers.google.com/web/updates/2016/10/capture-stream) which is not supported in videojs-record yet.

Marking this as a duplicate of #288

**Closed by thijstriemstra** 2019-11-24 20:34 UTC
Labels: duplicate
