### ISSUE TITLE
finishRecord event does not work on Safari

### ISSUE THREAD

**Issue by Zayn484** [collab-project/videojs-record#489] opened 2020-06-30 13:17 UTC
Hello, I'm using videojs-record with react and its working fine on Chrome. I tried with Safari but it doesn't work as it should. When recording video is stopped on Safari the finishRecord does not trigger in Safari which leads to this.player.recordedData as null:
```
    // user completed recording and stream is available
        this.player.on("finishRecord", () => {
            // recordedData is a blob object containing the recorded data that
            console.log("finished recording: ", this.player.recordedData);
        });

```
This event does not trigger on Safari when clicked on stop button but works fine on Chrome. Please make a fix for it.

## Browsers
Safari 13.1.1

## OS
Mac Catalina

## Videojs-Record
Version: 4.0.0

**Comment by dineshmaths1** [comment] 2020-07-09 14:09
which framework you are using ?

**Comment by Zayn484** [comment] 2020-07-13 05:38
@dineshmaths1 I'm using React.js

**Comment by thijstriemstra** [comment] 2020-07-13 13:22
can you reproduce this with any of the online demos?

**Comment by Zayn484** [comment] 2020-07-15 08:08
@thijstriemstra 
https://d33.gotomy.dev/editor/

Here is demo link, click on Video tab and click Add Video, there you will see Record Video option, click on that video recording will begin by triggering start button. When stop is clicked finishRecord event is triggered and there I added "Upload" button in controls. This works on chrome and firefox but not in Safari.

**Comment by thijstriemstra** [comment] 2020-07-15 11:02
@Zayn484 I meant any of the official examples: https://collab-project.github.io/videojs-record/#/examples

**Comment by Zayn484** [comment] 2020-07-24 05:36
@thijstriemstra https://collab-project.github.io/videojs-record/demo/video-only.html

**Comment by ignl** [comment] 2020-10-27 21:16
Hi,
I can also reproduce this with IOS 14 IPhone X and IPhone 6s and official demo. For IPhone stop and play buttons never appears and finishRecord is never called even if time has ran out. Ipad Pro seems to be working, however its video is not played by chrome, but that's another and probably browser issue...

**Comment by ignl** [comment] 2020-10-27 21:56
Unrelated, but a quick check  regarding corrupted video file yielded this: https://bugs.webkit.org/show_bug.cgi?id=216832
IOS 14.1 seems to still have this bug, hopefully it will be fixed soon.

**Comment by thijstriemstra** [comment] 2021-01-31 21:54
I tested this on macOS Safari 14.0.2 and macOS Safari Tech Preview 119 (Safari 14.1, WebKit 15611.1.10.1) and the `finishRecord` event triggers there properly.

If it also works on iOS 14.4 (I'll test later) I will consider this ticket fixed.

**Closed** 2021-01-31 23:44 UTC
Labels: known-browser-issue, safari-desktop
