### ISSUE TITLE
Record plugin maxlength exceeding

### ISSUE THREAD

**Issue by aurodeepg** [collab-project/videojs-record#425] opened 2019-12-10 21:11 UTC
## Description
The 'maxlength' option for 'record' plugin is not being honored. Recorded time exceeds limit.

## Steps to reproduce
Add 'wavesurfer' and 'record' plugins. Set 'msDisplayMax: 180' for 'wavesurfer' and 'maxlength: 180' for 'record'.

audioEngine used is 'lamejs'

### Expected
The recording should stop exactly at 180 seconds. Playback should also show 180 seconds/3 minutes

### Actual
Recording duration is constantly exceeding 180 seconds. It is recording close to 192 seconds

### Error output
No errors

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with? 
video.js : 7.6.5
videojs-record : 2.4.1
videojs-wavesurfer : 2.11.0
wavesurfer.js : 3.2.0
recordrtc : 5.5.8
#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
Chrome/Chromium
#### OSes
what platforms (operating systems and devices) are affected?
Windows 10

**Comment by thijstriemstra** [comment] 2020-02-02 23:56
you seem to be using a really old version of videojs-record: 2.4.1? can you try with the latest?

I could not reproduce it with 3.9.0:

![Screenshot from 2020-02-03 00-54-42](https://user-images.githubusercontent.com/305679/73617511-c9b16c80-461f-11ea-9db9-8c2af3d54d31.png)

```javascript
var options = {
    controls: true,
    width: 600,
    height: 300,
    fluid: false,
    plugins: {
        wavesurfer: {
            src:'live',
            waveColor: '#fffa00',
            progressColor: '#FAFCD2',
            debug: true,
            cursorWidth: 1,
            msDisplayMax: 180,
            hideScrollbar: true
        },
        record: {
            audio: true,
            video: false,
            maxLength: 180,
            debug: true,
            audioEngine: 'lamejs',
            audioWorkerURL: '../../node_modules/lamejs/worker-example/worker-realtime.js',
            audioSampleRate: 44100,
            audioBitRate: 128
        }
    }
};
```

**Comment by thijstriemstra** [comment] 2020-02-07 19:20
No feedback, closing.

**Closed by thijstriemstra** 2020-02-07 19:20 UTC
Labels: can-not-reproduce, needs-update, question
